name: 'Kolga Build'
description: 'This action is used to execute Kolga build step'
inputs:
  disable_cache:
    description: 'Disable buildx cache'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/andersinno/kolga:v3'
  entrypoint: /app/devops
  args:
    - create_images
  env:
    BUILDKIT_CACHE_DISABLE: ${{ inputs.disable_cache }}
